### ISSUE TITLE
onnx2caffe:AttributeError: permute_param

### ISSUE THREAD

**Issue by xautzxc** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#118]
run python convertCaffe.py by default params
error is as follows:
Traceback (most recent call last):
  File "convertCaffe.py", line 110, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 67, in convertToCaffe
    layers[id] = layer._to_proto()
  File "C:\Users\librazxc\Desktop\Ultra-Light-Fast-Generic-Face-Detector-1MB-master\caffe\MyCaffe.py", line 100, in _to_proto
    assign_proto(layer, k, v)
  File "C:\Users\librazxc\Desktop\Ultra-Light-Fast-Generic-Face-Detector-1MB-master\caffe\MyCaffe.py", line 29, in assign_proto
    is_repeated_field = hasattr(getattr(proto, name), 'extend')
AttributeError: permute_param

Any good suggestions？Thanks.

Install caffe-ssd version.

**Comment by AhmadMKhan** [comment]
hi , how did you solved it?

**Comment by qiqi-sunshine** [comment]
> hi , how did you solved it?

hello,have you solved it,please?
