### ISSUE TITLE
TypeError: ONNX node of type Slice is not supported. when convert simplified onnx model to caffe mode.

### ISSUE THREAD

**Issue by Royzon** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#131]
Thank you for sharing such a great project. I encountered this error when convert simplified onnx model to caffe model. can you help me to solve it? thank you very much.
Traceback (most recent call last):
  File "convertCaffe.py", line 110, in <module>
    convertToCaffe(graph, prototxt_path, caffemodel_path)
  File "convertCaffe.py", line 52, in convertToCaffe
    err.unsupported_op(node)
  File "Ultra-Light-Fast-Generic-Face-Detector-1MB/caffe/onnx2caffe/_error_utils.py", line 36, in unsupported_op
    "ONNX node of type {} is not supported.\n".format(node.op_type,)
TypeError: ONNX node of type Slice is not supported.

**Comment by xautzxc** [comment]
@Royzon You need to change a few lines of code before converting the model, please refer to　[model-to-ncnn](https://github.com/Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB/blob/master/ncnn/README.md#how-to-convert-pretrained-model-to-ncnn), then following the /caffe/readme.md

**Comment by Royzon** [comment]
thanks very much! sorry for my careless.
