### ISSUE TITLE
windows10 , python3.7 环境下执行报错..

### ISSUE THREAD

**Issue by gunC** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#14]
```
Traceback (most recent call last):
  File "H:/demo/Ultra-Light-Fast-Generic-Face-Detector-1MB/train.py", line 347, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "H:/demo/Ultra-Light-Fast-Generic-Face-Detector-1MB/train.py", line 139, in train
    for i, data in enumerate(loader):
  File "H:\worktool\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "H:\worktool\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "H:\worktool\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "H:\worktool\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "H:\worktool\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "H:\worktool\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "H:\worktool\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainAugmentation.__init__.<locals>.<lambda>'
```

priors nums:4420
2019-10-15 10:36:24,269 - root - INFO - Use Cuda.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "H:\worktool\Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "H:\worktool\Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

环境:
系统: windows10
python 3.7
pytorch 1.3.0

**Comment by gunC** [comment]
pytorch 1.3.0

**Comment by gunC** [comment]
`Traceback (most recent call last):
  File "H:/ai_demo/Ultra-Light-Fast-Generic-Face-Detector-1MB/train.py", line 347, in <module>
    device=DEVICE, debug_steps=args.debug_steps, epoch=epoch)
  File "H:/ai_demo/Ultra-Light-Fast-Generic-Face-Detector-1MB/train.py", line 139, in train
    for i, data in enumerate(loader):
  File "H:\worktool\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "H:\worktool\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "H:\worktool\Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "H:\worktool\Anaconda3\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "H:\worktool\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "H:\worktool\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "H:\worktool\Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'TrainAugmentation.__init__.<locals>.<lambda>'`

**Comment by Linzaer** [comment]
可能是win10 py多进程问题，不过我没在win下训练过抱歉，推理是正常的。

**Comment by 1604747003** [comment]
@Linzaer 这个windows的问题解决没有，当前的这个问题，求救

**Comment by 1604747003** [comment]
@Linzaer 亲亲
