### ISSUE TITLE
torch.nn.modules.module.ModuleAttributeError: 'SSD' object has no attribute 'module'

### ISSUE THREAD

**Issue by yikegaocaisheng** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#218]
#### 感谢开源如此棒的项目，但我在运行train-version-slim.sh时发生了如下错误，希望您有时间可以解决。
```python
Traceback (most recent call last):
  File "train.py", line 282, in <module>
    {'params': net.module.base_net.parameters(), 'lr': base_net_lr},
  File "/home/lin/anaconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 772, in __getattr__
    type(self).__name__, name))
torch.nn.modules.module.ModuleAttributeError: 'SSD' object has no attribute 'module'
```
*pytorch version==1.6.0*

**Comment by kevinwei30** [comment]
我這幾天試的時候也有遇到這問題，但如果有用GPU(net會過nn.DataParallel)似乎就不會有這個error，供參考。
```
(train.py : line 248 ~ 252)

# add multigpu_train
if torch.cuda.device_count() >= 1:
    cuda_index_list = [int(v.strip()) for v in args.cuda_index.split(",")]
    net = nn.DataParallel(net, device_ids=cuda_index_list)
    logging.info("use gpu :{}".format(cuda_index_list))
```
