### ISSUE TITLE
ultra_face_opencvdnn_inference with version-RFB-640.onnx weights does not work

### ISSUE THREAD

**Issue by MrDredD** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#239]
Hello! I'm trying to run **ultra_face_opencvdnn_inference** with **version-RFB-640.onnx** as a weights file, but getting this mesage:
`[ERROR:0] global /tmp/pip-req-build-ms668fyv/opencv/modules/dnn/src/onnx/onnx_importer.cpp (1876) handleNode DNN/ONNX: ERROR during processing node with 1 inputs and 1 outputs: [Exp]:(472)
Traceback (most recent call last):
  File "ultra_face_opencvdnn_inference.py", line 193, in <module>
    inference()
  File "ultra_face_opencvdnn_inference.py", line 148, in inference
    net = dnn.readNetFromONNX(args.onnx_path)  # onnx version
cv2.error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1887: error: (-2:Unspecified error) in function 'handleNode'
> Node [Exp]:(472) parse error: OpenCV(4.5.1) /tmp/pip-req-build-ms668fyv/opencv/modules/dnn/src/dnn.cpp:614: error: (-2:Unspecified error) Can't create layer "472" of type "Exp" in function 'getLayerInstance'
> 
`

Does anyone know, how to overcome this issue? Or does anybody successfully ran opencvdnn inference with RFB-640 model?

**Comment by Nerdary** [comment]
I have the exactly same error outputs. Both **version-RFB-640.onnx** and **version-RFB-320.onnx** do not work. I am using opencv 4.4.0 by the way.
