### ISSUE TITLE
torch转onnx转tensorflow，tensorflow测试时报错

### ISSUE THREAD

**Issue by longchr123** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#70]
非常感谢您的奉献，现在遇到点问题，请问是否有解决方案。

**1.环境：**
windows10,  cuda9.0,  onnx-tf=1.3.0,  tensorflow-gpu=1.12.0

代码中导入的包：

from skimage import io
import cv2
import onnx
import sys
import argparse
import torch.onnx
from onnx_tf.backend import prepare
from vision.ssd.config import fd_config
import tensorflow as tf
from skimage.transform import resize
import numpy as np
import onnxruntime as nxrun

**2.onnx 转tensorflow**

def convert_onnx_to_tf():
&nbsp;&nbsp;parser = argparse.ArgumentParser('convert onnx model to tensorflow model')
&nbsp;&nbsp;parser.add_argument('--onnx_model')#./models/onnx/version-RFB-320.onnx
&nbsp;&nbsp; args = parser.parse_args()
&nbsp;&nbsp;onnx_model = onnx.load(args.onnx_model)
&nbsp;&nbsp;tf_rep = prepare(onnx_model,strict=False)
&nbsp;&nbsp;with tf.Session() as sess:
&nbsp;&nbsp;&nbsp;&nbsp;sess.graph.as_default()
&nbsp;&nbsp;&nbsp;&nbsp;tf.import_graph_def(tf_rep.graph.as_graph_def(),name='')
&nbsp;&nbsp;&nbsp;&nbsp;inp = sess.graph.get_tensor_by_name(tf_rep.tensor_dict[tf_rep.inputs[0]].name)
&nbsp;&nbsp;&nbsp;&nbsp;print(inp)
&nbsp;&nbsp;&nbsp;&nbsp; out1 = sess.graph.get_tensor_by_name(tf_rep.tensor_dict[tf_rep.outputs[0]].name)
&nbsp;&nbsp; print(out1)
&nbsp;&nbsp;&nbsp;&nbsp;out2 = sess.graph.get_tensor_by_name(tf_rep.tensor_dict[tf_rep.outputs[1]].name)
&nbsp;&nbsp;&nbsp;&nbsp;print(out2)
&nbsp;&nbsp;tf_pb_path = args.onnx_model.replace('.onnx','.pb')
&nbsp;&nbsp;tf_rep.export_graph(tf_pb_path)

**3.pb文件测试**

def test_converted_pb():
&nbsp;&nbsp;pb_path = './models/onnx/version-RFB-320.pb'
&nbsp;&nbsp;detection_graph = tf.Graph()
&nbsp;&nbsp;with detection_graph.as_default():
&nbsp;&nbsp;&nbsp;&nbsp;od_graph_def = tf.GraphDef()
&nbsp;&nbsp;&nbsp;&nbsp;with tf.gfile.GFile(pb_path, 'rb') as fid:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;serialized_graph = fid.read()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;od_graph_def.ParseFromString(serialized_graph)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; tf.import_graph_def(od_graph_def, name='')
&nbsp;&nbsp;&nbsp;&nbsp;with tf.Session() as sess:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;input_node = sess.graph.get_tensor_by_name('input:0')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;output_scores = sess.graph.get_tensor_by_name('Softmax:0')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;output_boxes = sess.graph.get_tensor_by_name('concat_64:0')
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img = io.imread("./imgs/1.jpg")
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;img224 = resize(img / 255, (3, 240, 320), anti_aliasing=True)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(img224.shape)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ximg = img224[np.newaxis, :, :, :]
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(ximg.shape)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; image = ximg.astype(np.float32)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;out = sess.run([output_scores,output_boxes],feed_dict={input_node:image})
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;print(out)

**4.报错如下：**

Traceback (most recent call last):
  File "E:/Lcr/Workspace/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/convert_model.py", line 156, in <module>
    test_converted_pb()
  File "E:/Lcr/Workspace/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/convert_model.py", line 148, in test_converted_pb
    out = sess.run([output_scores,output_boxes],feed_dict={input_node:image})
  File "C:\Software\python36\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
    run_metadata_ptr)
  File "C:\Software\python36\lib\site-packages\tensorflow\python\client\session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Software\python36\lib\site-packages\tensorflow\python\client\session.py", line 1328, in _do_run
    run_metadata)
  File "C:\Software\python36\lib\site-packages\tensorflow\python\client\session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[node convolution (defined at E:/Lcr/Workspace/Ultra-Light-Fast-Generic-Face-Detector-1MB-master/convert_model.py:130)  = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 1, 2, 2], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Pad, split)]]
	 [[{{node concat_54/_13}} = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_6347_concat_54", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

**请问这个错误是否有解决方案？**

**Comment by longchr123** [comment]
不知为何突然问题好了，如果有遇到此问题，可以尝试一下这个方案https://github.com/tensorflow/tensorflow/issues/24828
