### ISSUE TITLE
AttributeError: 'SSD' object has no attribute 'module'

### ISSUE THREAD

**Issue by Dengxianshuai** [Linzaer/Ultra-Light-Fast-Generic-Face-Detector-1MB#93]
下载数据集之后运行sh train-version-slim.sh出现这样的错误，请大佬指教(刚看pytorch)
Traceback (most recent call last):
  File "train.py", line 284, in <module>
    {'params': net.module.base_net.parameters(), 'lr': base_net_lr},
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'SSD' object has no attribute 'module'

**Comment by Dengxianshuai** [comment]
![image](https://user-images.githubusercontent.com/30050929/69790244-1716f500-11fd-11ea-94da-8df2ab6ca614.png)
找到bug了，把module去掉就行了
